gText_Kector_Welcome::
	.string "Welcome Initiative!\p"
	.string "If you see this message that means\n"
	.string "you've successfully completed the\l"
	.string "screening test, and we invite you to\l"
	.string "join our program to become an official\l"
	.string "M.O.D. member.\p"
	.string "My name is Professor Kector, One of\n"
	.string "the last remaining Pokemon Experts\l"
	.string "of this world, also known as Pokemon\l"
	.string "Professors.\p"
	.string "$"

gText_Kector_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Kector_MainSpeech::
	.string "This world used to inhabit over a\n"
	.string "1000 different Pokemons, many yet\l"
	.string "undiscovered. That was until the\l"
	.string "pokemon suddenly disappeared\l"
	.string "12 years ago.\p"
	.string "Just as mysteriously, they have been\n"
	.string "returning to our world a little over\l"
	.string "2 years ago. 8 years after our great\l"
	.string "LEADER has taken full control of the\l"
	.string "world order and brought peace to our\l"
	.string "lands.\p"
	.string "$"

gText_Kector_LawChange::
	.string "When they reappeared, many people\n"
	.string "jumped on the opportunity to own or\l"
	.string "re-own these creatures.\p"
	.string "However, the LEADER rightfully\n"
	.string "anticipated the dangers these\l"
	.string "creatures could bring to the world\l"
	.string "peace he had created.\l"
	.string "So, it became forbidden to own\l"
	.string "pokemon except for trusted MOD\l"
	.string "members.\p"
	.string "$"

gText_Kector_Screening::
	.string "As you might understand, the change\n"
	.string "in law meant that we get a lot of\l"
	.string "applications.\p"
	.string "Many people like to own the power of\n"
	.string "controlling pokemon, but only few are\l"
	.string "actually worthy of handling it.\l"
	.string "You have set your first step into\l" 
	.string "proving you're capable of owning\l"
	.string "pokemon.\p"
	.string "However, if we ever find out you abuse\l"
	.string "these powers we gave you, there will\l"
	.string "be dire consequences...\l"
	.string "Consequences that even your pokemon\n"
	.string "can't protect you from.\p"
	.string "$"

gText_Kector_InformationNeeded::
	.string "Now, we do require a bit more\n"
	.string "information from you before you can\l"
	.string "enter our training facility.\p"
	.string "It might seem strange we only ask\l"
	.string "this now, but the LEADER believes\l"
	.string "in equal opportunity for all\l"
	.string "his people.\p"
	.string "So with that being said, first\n"
	.string "things first.\p"
	.string "$"

gText_Kector_AndYouAre::
	.string "What is your gender?$"

gText_Kector_BoyOrGirl::
	.string "Are you a Man?\n"
	.string "Or are you a Woman?$"

gText_Kector_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Kector_SoItsPlayer::
	.string "{PLAYER}{KUN}... written like that?$"

gText_Kector_YourePlayer::
	.string "Great, thank you!\n"
	.string "That is all I need!\p"
	.string "Hope to see you at M.O.D. Headquarters\n"
	.string "soon {PLAYER}{KUN}, at the Cliff To\l"
	.string "Nowhere, the building is hard to miss\l"
	.string "so I'm sure you'll find a way to get\l"
	.string "here.\p"
	.string "$"

gText_Kector_AreYouReady::
	.string "You still have a long road ahead\n"
	.string "before you'll be allowed to use\l"
	.string "pokemon, but if you work hard and\l"
	.string "listen to the rules you and your\l"
	.string "fellow initiatives will start your\l"
	.string "true adventure soon enough.\p"
	.string "May your fire burn bright!\p"
	.string "$"