Empty_MapScripts::
	.byte 0


Debug_Trigger_TestFlying::
	return


# 8 "data/maps/Empty/scripts.pory"
CommonMovement_Notice:
# 9 "data/maps/Empty/scripts.pory"
	emote_exclamation_mark
	step_end

# 12 "data/maps/Empty/scripts.pory"
CommonMovement_NoticeUp:
# 13 "data/maps/Empty/scripts.pory"
	face_up
# 14 "data/maps/Empty/scripts.pory"
	emote_exclamation_mark
	step_end

# 17 "data/maps/Empty/scripts.pory"
CommonMovement_NoticeDown:
# 18 "data/maps/Empty/scripts.pory"
	face_down
# 19 "data/maps/Empty/scripts.pory"
	emote_exclamation_mark
	step_end

# 22 "data/maps/Empty/scripts.pory"
CommonMovement_NoticeLeft:
# 23 "data/maps/Empty/scripts.pory"
	face_left
# 24 "data/maps/Empty/scripts.pory"
	emote_exclamation_mark
	step_end

# 27 "data/maps/Empty/scripts.pory"
CommonMovement_NoticeRight:
# 28 "data/maps/Empty/scripts.pory"
	face_right
# 29 "data/maps/Empty/scripts.pory"
	emote_exclamation_mark
	step_end

# 32 "data/maps/Empty/scripts.pory"
CommonMovement_FacePlayer:
# 33 "data/maps/Empty/scripts.pory"
	face_player
	step_end

# 36 "data/maps/Empty/scripts.pory"
CommonMovement_LookUp:
# 37 "data/maps/Empty/scripts.pory"
	face_up
	step_end

# 40 "data/maps/Empty/scripts.pory"
CommonMovement_LookDown:
# 41 "data/maps/Empty/scripts.pory"
	face_down
	step_end

# 44 "data/maps/Empty/scripts.pory"
CommonMovement_LookLeft:
# 45 "data/maps/Empty/scripts.pory"
	face_left
	step_end

# 48 "data/maps/Empty/scripts.pory"
CommonMovement_LookRight:
# 49 "data/maps/Empty/scripts.pory"
	face_right
	step_end

# 52 "data/maps/Empty/scripts.pory"
CommonMovement_WalkUp1:
# 53 "data/maps/Empty/scripts.pory"
	walk_up
	step_end

# 56 "data/maps/Empty/scripts.pory"
CommonMovement_WalkDown1:
# 57 "data/maps/Empty/scripts.pory"
	walk_down
	step_end

# 60 "data/maps/Empty/scripts.pory"
CommonMovement_WalkLeft1:
# 61 "data/maps/Empty/scripts.pory"
	walk_left
	step_end

# 64 "data/maps/Empty/scripts.pory"
CommonMovement_WalkRight1:
# 65 "data/maps/Empty/scripts.pory"
	walk_right
	step_end

# 68 "data/maps/Empty/scripts.pory"
CommonMovement_WalkUpSlow1:
# 69 "data/maps/Empty/scripts.pory"
	walk_slow_up
	step_end

# 72 "data/maps/Empty/scripts.pory"
CommonMovement_WalkDownSlow1:
# 73 "data/maps/Empty/scripts.pory"
	walk_slow_down
	step_end

# 76 "data/maps/Empty/scripts.pory"
CommonMovement_WalkLeftSlow1:
# 77 "data/maps/Empty/scripts.pory"
	walk_slow_left
	step_end

# 80 "data/maps/Empty/scripts.pory"
CommonMovement_WalkRightSlow1:
# 81 "data/maps/Empty/scripts.pory"
	walk_slow_right
	step_end

# 84 "data/maps/Empty/scripts.pory"
CommonMovement_WalkOutOfTheWayUp:
# 85 "data/maps/Empty/scripts.pory"
	walk_up
# 86 "data/maps/Empty/scripts.pory"
	face_down
	step_end

# 89 "data/maps/Empty/scripts.pory"
CommonMovement_WalkOutOfTheWayDown:
# 90 "data/maps/Empty/scripts.pory"
	walk_down
# 91 "data/maps/Empty/scripts.pory"
	face_up
	step_end

# 94 "data/maps/Empty/scripts.pory"
CommonMovement_WalkOutOfTheWayLeft:
# 95 "data/maps/Empty/scripts.pory"
	walk_left
# 96 "data/maps/Empty/scripts.pory"
	face_right
	step_end

# 99 "data/maps/Empty/scripts.pory"
CommonMovement_WalkOutOfTheWayRight:
# 100 "data/maps/Empty/scripts.pory"
	walk_right
# 101 "data/maps/Empty/scripts.pory"
	face_left
	step_end

# 104 "data/maps/Empty/scripts.pory"
CommonMovement_WalkUpAndNotice:
# 105 "data/maps/Empty/scripts.pory"
	walk_up
# 106 "data/maps/Empty/scripts.pory"
	emote_exclamation_mark
	step_end

# 109 "data/maps/Empty/scripts.pory"
CommonMovement_WalkDownAndNotice:
# 110 "data/maps/Empty/scripts.pory"
	walk_down
# 111 "data/maps/Empty/scripts.pory"
	emote_exclamation_mark
	step_end

# 114 "data/maps/Empty/scripts.pory"
CommonMovement_WalkLeftAndNotice:
# 115 "data/maps/Empty/scripts.pory"
	walk_left
# 116 "data/maps/Empty/scripts.pory"
	emote_exclamation_mark
	step_end

# 119 "data/maps/Empty/scripts.pory"
CommonMovement_WalkRightAndNotice:
# 120 "data/maps/Empty/scripts.pory"
	walk_right
# 121 "data/maps/Empty/scripts.pory"
	emote_exclamation_mark
	step_end
